### ISSUE TITLE
Enhance models.yml

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5588]
Some documentation about the structure is missing. especially:
- What does `replacement` do
- What are formats to specify relations (multiple ones are used....)
- `type: structured-tag`

Another things to fix:
- The default weights are usually much higher, like 10000 (this is sufficient to not calculate max+1 in the DB). Affects motion_submitter, speaker, agenda_item, ...
- Mediafile has many read_only fields, that must be marked as such

**Comment by normanjaeckel** [comment]
`replacement` is what `<...>` was in former models.txt inside the name of a template field or structured field. In OpenSlices Backend code we use a `$` for this placeholder. The term `replacement` came from @ostcar and might be already used in autoupdate-client communication.

Formats for relations: Maybe one can have a look at some examples and then write an meaningful documentation.

Structured tag is a structured field where the content of the replacment / placeholder is not an id related to something (like meeting id) but an arbitrary tag like `web` ´italic` and thelike. I think we need a different behavior here.

Defaults and read-only fields might be changed, no problem.

**Comment by ostcar** [comment]
Is there something I should do?

I don't think that I used the term "replacement" in the autoupdate-code. And even when I did, you can still change it.

The autoupdate-code runs the code-generation not at runtime. It has to be called manually. So if you change the models.yml and break my code, the autoupdate-service will continue to work.

**Comment by FinnStutzenstein** [comment]
The `<...>` part was to indicate how the template value has to be interpret and was more something like a documentational thing.

I would prefer no differentiating between a structured field and structured tag. Do you need it at some place? Also the same for `template` and `structured-field`: You can use this unified format for structured-relations and template (this is the same as we are using in the client-autoupdate requests):

```
user_id:
    type: relation
    to:
      collection: user
      field:
        name: submitted_motion_$_ids
        replacement: meeting_id
        type: structured-field
        values:
          type: relation
          through:
          - motion_id
...
amendment_paragraph_$:
    type: structured-field
    replacement: paragraph_number
    values: HTML
```

You first denote, that there is a structured field, and within `values` you specify how to handle the field values. This approach seperated the logic for handing structured fields (relpacing templates, ...) and the relations handling (if any).
