### ISSUE TITLE
Server does not start up: Wait for another process to build up the cache...

### ISSUE THREAD

**Issue by noresistence** [OpenSlides/OpenSlides#5625]
We just tried to deploy openslides with docker-compose. Building the services works fine, and all services start running, but the server does not complete its startup. It hangs with the message
```
[...] Wait for another process to build up the cache...
```

This message looks like it is supposed to only show up if there are several server instances running, but we do only start one instance (to the best of our knowledge).

For reference, this is our docker-compose file. We have slightly modified it to suit our environment and deployment process.

<details>
<summary> docker-compose.yml </summary> 

```
# This configuration was created from a template file.  Before making changes,
# please make sure that you do not have a process in place that would override
# your changes in the future.  The accompanying .env file might be the correct
# place for customizations instead.
version: '3.4'

x-osserver:
  &default-osserver
  image: $DOCKER_REPO/openslides-server:latest
  networks:
    - front
    - back
    - mail
  volumes:
    - openslides_secrets:/run/secrets
  restart: always
x-osserver-env: &default-osserver-env
    AMOUNT_REPLICAS: 1
    AUTOUPDATE_DELAY: 1
    DEMO_USERS: ""
    CONNECTION_POOL_LIMIT: 100
    DATABASE_HOST: "pgbouncer"
    DATABASE_PASSWORD: $DATABASE_PASSWORD
    DATABASE_PORT: 5432
    DATABASE_USER: "openslides"
    DEFAULT_FROM_EMAIL: "noreply@example.net"
    DJANGO_LOG_LEVEL: "INFO"
    EMAIL_HOST: "mailserver"
    EMAIL_HOST_PASSWORD: ""
    EMAIL_HOST_USER: ""
    EMAIL_PORT: 25
    ENABLE_ELECTRONIC_VOTING: "False"
    ENABLE_SAML: "False"
    INSTANCE_DOMAIN: "${HOSTNAME}"
    JITSI_DOMAIN: ""
    JITSI_ROOM_PASSWORD: ""
    JITSI_ROOM_NAME: ""
    OPENSLIDES_LOG_LEVEL: "INFO"
    REDIS_CHANNLES_HOST: "redis-channels"
    REDIS_CHANNLES_PORT: 6379
    REDIS_HOST: "redis"
    REDIS_PORT: 6379
    REDIS_SLAVE_HOST: "redis-slave"
    REDIS_SLAVE_PORT: 6379
    REDIS_SLAVE_WAIT_TIMEOUT: 10000
    RESET_PASSWORD_VERBOSE_ERRORS: "False"
x-pgnode: &default-pgnode
  image: $DOCKER_REPO/openslides-repmgr:latest
  networks:
    - dbnet
  labels:
    org.openslides.role: "postgres"
  restart: always
x-pgnode-env: &default-pgnode-env
  REPMGR_RECONNECT_ATTEMPTS: 30
  REPMGR_RECONNECT_INTERVAL: 10
  REPMGR_WAL_ARCHIVE: "on"

services:
  server:
    << : *default-osserver
    # Below is the default command.  You can uncomment it to override the
    # number of workers, for example:
    # command: "gunicorn -w 8 --preload -b 0.0.0.0:8000
    #   -k uvicorn.workers.UvicornWorker openslides.asgi:application"
    #
    # Uncomment the following line to use daphne instead of gunicorn:
    # command: "daphne -b 0.0.0.0 -p 8000 openslides.asgi:application"
    depends_on:
      - server-setup
    environment:
      << : *default-osserver-env
      
    

  server-setup:
    << : *default-osserver
    entrypoint: /usr/local/sbin/entrypoint-db-setup
    environment:
      << : *default-osserver-env
      
      
      
    depends_on:
      - pgbouncer
      - redis
      - redis-slave
      - redis-channels

  client:
    image: $DOCKER_REPO/openslides-client:latest
    restart: always
    depends_on:
      - server
    networks:
      - front
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${HOSTNAME}"
      - "traefik.docker.network=web"
      - "traefik.main.frontend.rule=Host:${HOSTNAME}"
      - "traefik.main.port=80"


  pgnode1:
    << : *default-pgnode
    environment:
      << : *default-pgnode-env
      REPMGR_NODE_ID: 1
      REPMGR_PRIMARY: # This is the primary
    volumes:
      - "dbdata1:/var/lib/postgresql"



  pgbouncer:
    environment:
      - PG_NODE_LIST=pgnode1
    image: $DOCKER_REPO/openslides-pgbouncer:latest
    restart: always
    networks:
      back:
        aliases:
          - db
          - postgres
      dbnet:
  postfix:
    image: $DOCKER_REPO/openslides-postfix:latest
    restart: always
    environment:
      MYHOSTNAME: "localhost"
      RELAYHOST: "localhost"
    networks:
      - back
  redis:
    image: redis:alpine
    restart: always
    networks:
      back:
        aliases:
          - rediscache
  redis-slave:
    image: redis:alpine
    restart: always
    command: ["redis-server", "--save", "", "--slaveof", "redis", "6379"]
    depends_on:
      - redis
    networks:
      back:
        aliases:
          - rediscache-slave
    
  redis-channels:
    image: redis:alpine
    restart: always
    networks:
      back:
  media:
    image: $DOCKER_REPO/openslides-media-service:latest
    environment:
      - CHECK_REQUEST_URL=server:8000/check-media/
    restart: always
    networks:
      front:
      back:
    # Override command to run more workers per task
    # command: ["gunicorn", "-w", "4", "--preload", "-b",
    #   "0.0.0.0:8000", "src.mediaserver:app"]

volumes:
  dbdata1:
  openslides_secrets:
    external: true


networks:
  front:
  back:
  dbnet:
  web:
    external: true
  mail:
    external: true

secrets:
  django:
    file: ./secrets/django.env
  
  
  

# vim: set: sw=2 et:

```

</details>
