### ISSUE TITLE
Emails cannot be sent (OpenSlides 4)

### ISSUE THREAD

**Issue by davidhuber24** [OpenSlides/OpenSlides#6469]
**Describe the bug**
OpenSlides is unable to send emails. For example, if I click on Forgot Password and have an email sent to me, the Web frontend tells me "sent" however the following message appears in the log:

```
root@openslides:/opt/openslides# docker logs openslides_backendAction_1
 
datastoreWriter:9011 is available
[2022-07-25 18:23:44 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-07-25 18:23:44 +0000] [1] [INFO] Listening at: http://0.0.0.0:9002 (1)
[2022-07-25 18:23:44 +0000] [1] [INFO] Using worker: sync
[2022-07-25 18:23:44 +0000] [10] [INFO] Booting worker with pid: 10
ERROR:openslides_backend.action.action:General send mail exception: [Errno 99] Cannot assign requested address
```

Here is a part of the Docker-compose file as well as the .env file:
```
backendAction:
  image: ghcr.io/openslides/openslides/openslides-backend:latest
  env_file:
    - ./.env
  depends_on:
    - datastoreWriter
    - auth
    - media
```
```
root@openslides:/opt/openslides# cat .env 
EMAIL_HOST = mysmtp.domain.com
EMAIL_PORT = 465
EMAIL_HOST_USER = openslides@domain.com
EMAIL_HOST_PASSWORD = password
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = openslides@domain.com
```
Note: These exact values works with OpenSlides 3 (in the settings.py file).

I can also see, that the variables from the .env files are being used by the container:
```
root@openslides:/opt/openslides# docker exec -u 0 -it openslides_backendAction_1 /bin/bash
root@a5adcbc3f0d8:/app# env | grep MAIL
EMAIL_HOST=mysmtp.domain.com
EMAIL_USE_TLS=False
EMAIL_HOST_USER=openslides@domain.com
EMAIL_USE_SSL=True
EMAIL_TIMEOUT=10
EMAIL_PORT=465
EMAIL_HOST_PASSWORD=password
EMAIL_CONNECTION_SECURITY=NONE
DEFAULT_FROM_EMAIL=openslides@domain.com
EMAIL_ACCEPT_SELF_SIGNED_CERTIFICATE=false
```
The backendAction container is not able to perform any networking-related commands, like "ping", "ip a", ...
However I figured out, the DNS (of the container) is not working. "apt update" returns DNS-related errors.
I put the Google DNS server in the resolv.conf but it still didn't work. "curl 1.1.1.1" also returns nothing.

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

1. Follow the instructions from your GitHub (Download the openslides file and execute it...
2. docker-compose up (-d)
3. Try to send E-Mails 
4. This wont work
5. Create the .env file 
6. Edit the docker-compsoe file to use the .env file
7. Try to send emails again
8. Check to logs

**Expected behavior**
Receiving the E-Mail, no errors in the log files.

**System information**

- OpenSlides-Version: 4, latest
- Python Version: Python 3.10.4
- Device: Server: Ubuntu 22.04 VM, 2 Cores, 4 GB RAM, 60 GB Disk, Client(s): MacBook Pro 2021 M1 Pro, Chrome 100

**Comment by ditschi** [comment]
I can confirm this issue.  When creating a new (test) user  (with a provided mail address )  I tried to sen a Invitation mail. 

that results in the messsage: 
`No emails were send. The user has no email, so the invitation email could not be send.`

Which is just not true. the mail is clearly configured in the web ui. Also `./openslides  get user`  shows that the user has a mail address.

The config  in the docker compose (and PW from .env file)  I did as described in https://github.com/OpenSlides/openslides-manage-service#email

```yaml
      EMAIL_HOST: smtp.domain.de
      EMAIL_PORT: 465
      EMAIL_HOST_USER: openslides@domain.de
      # EMAIL_HOST_PASSWORD: from .env file
      EMAIL_CONNECTION_SECURITY: "SSL/TLS"  # This can also be "NONE" or "STARTTLS".
      EMAIL_TIMEOUT: 5  # Timeout in seconds for blocking operations like the connection attempt.
      EMAIL_ACCEPT_SELF_SIGNED_CERTIFICATE: "false"  # Or "true" of course.
      DEFAULT_FROM_EMAIL: openslides@domain.de
      OPENSLIDES_BACKEND_COMPONENT: action
```
