### ISSUE TITLE
Documentation SMTP OpenSlides 4

### ISSUE THREAD

**Issue by InterFelix** [OpenSlides/OpenSlides#6556]
**Is your feature request related to a problem? Please describe.**
I need to use a SMTP inbox for outbound mail. In previous versions of OpenSlides, this was well documented, however I could not find any information about this for OpenSlides 4.

**Describe the solution you'd like**
Provide clear documentation about how to configure SMTP outbound mail.

**Additional context**
I already tried the old environment variables without any luck.

**Comment by peb-adr** [comment]
Hello!
https://github.com/OpenSlides/OpenSlides/blob/main/INSTALL.md#email
Have you seen this? Or did you have problems following it?

**Comment by peb-adr** [comment]
Also taking a look at the (there referenced)
https://github.com/OpenSlides/openslides-backend/blob/3cecc596b3b4866d5a243ee1335763125c61ee38/openslides_backend/action/mixins/send_email_mixin.py#L38
should give you a good understanding of how the env vars are being used.
And from what you said I think you should be able to achieve your goal with this ;)

**Comment by InterFelix** [comment]
> Hello! https://github.com/OpenSlides/OpenSlides/blob/main/INSTALL.md#email Have you seen this? Or did you have problems following it?

Now that's a great suprise... I guess I was just too tired to look in the most obvious place possible.
I would still suggest adding this section to the default config.yml file, so people can just uncomment the relevant section.

**Comment by mkasimd** [comment]
That said, setting it up like that didn't work in my case either.. When trying to send an invitation email (the user does have an email address set up in its profile):

```
server process is running
process type: user.send_invitation_email
--
No emails were send. The user has no email, so the invitation email could not be send.
```
Also "reset password" didn't trigger an email either. Looking into the logs of the set up SMTP server, no requests were received there. I tested the credentials & port on a different email client, so that's not the issue here.

The resulting parts in the docker-compose.yml look like this:

```
backendAction:
    image: ghcr.io/openslides/openslides/openslides-backend:4.0.0
    depends_on:
      - datastoreWriter
      - auth
      - media
      - vote
      - postgres
    environment:
      << : *default-environment
      DEFAULT_FROM_EMAIL: no-reply@example.com
      EMAIL_ACCEPT_SELF_SIGNED_CERTIFICATE: "false"
      EMAIL_CONNECTION_SECURITY: SSL/TLS
      EMAIL_HOST: mail.example.com
      EMAIL_HOST_PASSWORD: 3X4mP13pa55+fr
      EMAIL_HOST_USER: no-reply@example.com
      EMAIL_PORT: "465"
      EMAIL_TIMEOUT: "5"
      OPENSLIDES_BACKEND_COMPONENT: action
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password
```

Any idea what's going on here`? Perhaps, I'm missing something? 🤔
