### ISSUE TITLE
Enable alpn challenge on proxy

### ISSUE THREAD

**Issue by oliverpool** [OpenSlides/OpenSlides#6560]
**Is your feature request related to a problem? Please describe.**
I am trying to deploy openslides along other web services. Using nginx `ssl_preread_server_name` I split the https traffic depending on the server name (nginx is managing the https certificates for the other hostnames).

However the openslides docker composition cannot get an https certificate via letsencrypt:
- the http port is not exposed with the default compose file

https://github.com/OpenSlides/openslides-manage-service/blob/3241faa5f13bde9b1f932970531321fe1b197d5f/pkg/config/default-docker-compose.yml#L38

- the tls-alpn challenge is disabled

https://github.com/OpenSlides/OpenSlides/blob/5da8a6a529b06875ee94b8f2afcbc8411d62d735/proxy/caddy_base.json#L12

**Describe the solution you'd like**
Activate the tls-alpn challenge.

**Describe alternatives you've considered**
Expose the http port via the compose file (however it means that I have to add more config to my nginx conf).

**Additional context**
I am using the generated docker-compose.yml file, with the following `config.yml`
```
port: 8002

enableAutoHTTPS: true
enableLocalHTTPS: false
services:
  proxy:
    environment:
      EXTERNAL_ADDRESS: my.domain.tld
```

**Comment by oliverpool** [comment]
Current workaround:
```
port: 8002
services:
  proxy:
    AdditionalContent:
      ports:
        - 127.0.0.1:8002:8000
        - 127.0.0.1:8003:8001
```

The compose file gets a duplicate, 
```
    ports:
      - 127.0.0.1:8002:8000
    ports:
    - 127.0.0.1:8002:8000
    - 127.0.0.1:8003:8001
```

but the merge is correct.
