### ISSUE TITLE
email error 'user has no email' but actually the user has "No emails were send. The user has no email, so the invitation email could not be send."

### ISSUE THREAD

**Issue by im-fabian** [OpenSlides/OpenSlides#6585]
**Describe the bug**
I have set up the mailserver according documentation. When I then try to send an email to an newly created user within openslided I get the message "No emails were send. The user has no email, so the invitation email could not be send." altrough the user definitely have a email.

**How to Reproduce**

1. Go to Accounts.
2. Add an Account with an email.
3. On the profile page of the account on the tree dots klick "send invitation email"

**Expected behavior**
The email should be sended. No error should be thrown.

**System information**

- OpenSlides-Version: 4.0.1-main-20230424-19b6cce
- Device: MacBook Pro 16" 2021.
- OS: macOS, current Version
- Browser: Safari & Firefox
- Browser-Version: current versions

**Additional context**
```
(Excerpt from docker-compose.yml)

   environment:
      << : *default-environment
      OPENSLIDES_BACKEND_COMPONENT: action
      EMAIL_HOST: "smtp-relay.sendinblue.com"
      EMAIL_PORT: "587"
      EMAIL_HOST_USER: "*************"
      EMAIL_HOST_PASSWORD: "***********"
      EMAIL_CONNECTION_SECURITY: "SSL/TLS"  # This can also be "NONE" or "STARTTLS".
      EMAIL_TIMEOUT: "5"  # Timeout in seconds for blocking operations like the connection attempt.
      EMAIL_ACCEPT_SELF_SIGNED_CERTIFICATE: "false"  # Or "true" of course.
```

**Screenshots**

![Fabian_Müller_-_OpenSlides](https://user-images.githubusercontent.com/31921275/236636714-779eb3d7-7e7c-4515-b848-25ff696e4ef8.jpg)
