### ISSUE TITLE
Stuck in "Data will be loaded" sometimes

### ISSUE THREAD

**Issue by sistason** [OpenSlides/OpenSlides#6804]
Sometimes, Openslides is stuck in "Data will be loaded". Might be just Firefox, but Ctrl+F5 / Private Tab / other Browser solves the problem.

It's happening often (per meeting 1 person has it of ~20) and it's just "things that happen with Openslides". I'd hoped it went away with OS4, but it did not. I'd like to primarily open this Bug Report to work on it with you, that it does not stay "just something Openslides does", as some of my users like to call it :)

I saw in the logs that while this is happening:
Firefox Console: 
![image](https://github.com/user-attachments/assets/06bc8a3a-86e0-42cd-bed5-7611f39086d1)
![Screenshot from 2024-08-26 20-46-37](https://github.com/user-attachments/assets/adf7b30f-14cb-45a4-a7ba-7627371d83d8)

Server: 
```
datastoreReader-1   | [2024-08-26 18:43:32 +0000] [13] [INFO] GET-request: {'fqid': 'user/XXX', 'mapped_fields': ['id', 'username', 'password', 'is_active', 'meta_deleted']}
auth-1              | 2024-08-26T18:43:32.453Z http://openslides.XXXXX.de: POST -- /system/auth/who-am-i/
auth-1              | 2024-08-26T18:43:56.890Z Metric: {"sessions":209,"users":48}
```

So it seems the Client sends the whoami and the server receives it, but the response is lost?
Is it a problem that there is a http://openslides... in the logs, not https://? (the logs look the same with the http also for the working clients)

**How to Reproduce**
Steps to reproduce the behavior: No idea ;) Usually: Wait a bit until pressing F5

**System information**
- OpenSlides 4.1.14
- Ubuntu 24 Firefox 128.0.3
What I could imagine is the compose setting. openslides-config.yaml:
```
host: 127.0.0.1
port: 8000
enableLocalHTTPS: false
services:
  proxy:
    AdditionalContent:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "webproxy"
        traefik.http.routers.openslides.rule: "Host(`openslides.XXXXX.de`)"
        traefik.http.routers.openslides.entrypoints: "websecure"
        traefik.http.routers.openslides.tls.certresolver: "myresolver"
        traefik.http.routers.openslides.service: "openslides-service"
        traefik.http.services.openslides-service.loadbalancer.server.port: "8000"

        traefik.http.services.openslides-manage.loadbalancer.server.port: "8000"
        traefik.http.services.openslides-manage.loadbalancer.server.scheme: "h2c"
        traefik.http.routers.openslides-manage.service: "openslides-manage"
        traefik.http.routers.openslides-manage.rule: "Host(`openslides.XXXXX.de`) && PathPrefix(`/Manage/`)"
```
using together with a docker-compose.override.yaml to inject the webproxy network to the proxy-service. Everything works but sometimes this hickup.
Caddy also logspams with `proxy-1  | {"level":"error","ts":1724698529.5201952,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}` but that seems to be just normal behavior as far as I read the Issues :)

**Additional context**
related: #6260

**Comment by rrenkert** [comment]
Thanks for reporting your problem!
You are using a traefik as proxy in front of the caddy-proxy. Did you try OS4 without this additional proxy?
As you say "other users", I guess you have a production build? Do all components in your setup support http2?

**Comment by sistason** [comment]
Thanks for the response.

I did not try OS4 without this proxy. As I use Traefik for all services in the infrastructure, I wanted to do the https/letsencrypt part in a standardized way, that's the only reason for it.
The Traefik container listens directly on 80/443, so there are no additional components in between than Treaefik.

Yes this is a production setup, usually 1 person in a group "cannot connect to Openslides right now" and opens it on their mobile phone or in another browser, then. I have congress of 200 ppl incoming and expect "fun times" with that, but we're used to Openslides Problems and some retrying is considered normal.


Do you expect traefik to have interfacing problems with Caddy, or something with http2 as "more likely" in mind, which one should I try to inspect first?

**Comment by rrenkert** [comment]
We use HAproxy as proxy in front of the caddy without any problems, so I would recommend to try without the traefik or try HAproxy instead. We know that Apache2 has issues with proxying http2, so maybe its the same with traefik?
Can you give me more details about your setup?

**Comment by sistason** [comment]
I learned a bit caddy and set it up to do https and configured the other services in order for the setup to work (https://github.com/OpenSlides/openslides-proxy/issues/17).

I think I will switch to caddy-only and see if the errors are reproduceable there. On the weekend, a 40 people assembly went by without any issues, so its in Heisenbug territory...

Regarding more details, I wanted to try out caddy first so we can rule out issues with traefik forwarding. That sounds like they could be the reason, as there seems to be traffic getting lost on the way back.

Our setup does additionally contain a SaToSa SAML->OIDC gateway, which also sounds like that could introduce session timeout issues or something. But I have not seen any indicators in that direction, so I will check out caddy/traefik first

**Comment by sistason** [comment]
Switched to Caddy only, but it still occurs sometimes the same way as before. These logs happen when affected people reload their browsers (and still getting stuck in "Daten werden geladen"):

```
auth-1              | 2024-09-24T15:40:32.242Z http://openslides.linksjugend-solid.de: POST -- /system/auth/who-am-i/
datastoreReader-1   | [2024-09-24 15:40:32 +0000] [13] [INFO] GET-request: {'fqid': 'user/1393', 'mapped_fields': ['id', 'username', 'password', 'is_active', 'meta_deleted']}
auth-1              | 2024-09-24T15:40:43.542Z Metric: {"sessions":2866,"users":216}
proxy-1             | {"level":"error","ts":1727192448.963209,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
```

15:40:32 - Auth+datastoreReader
15:40:48 - proxy (timestamp converted)
(does not seem to be any relevant timeout related)

The proxy is full (every few seconds) of the `incomplete response, context canceled` errors.

User sent me this screenshot of their inspector. The 2 request timeout, e.g. stay greyed out and get aborted on page reload:
![5447364888067431345](https://github.com/user-attachments/assets/b8ffbaf8-acc9-444d-bd53-36b1df1d740b)

I cannot say it only happens on Firefox, but all people I saw were using Firefox. I'm on 128.0.3.

What would you suggest next?

**Comment by sistason** [comment]
openslides-config.yml:
```
---
host: 0.0.0.0

enableLocalHTTPS: false
enableAutoHTTPS: True

defaults:
  containerRegistry: ghcr.io/openslides/openslides
  tag: latest

defaultEnvironment:
  OPENSLIDES_LOGLEVEL: info
  OPENSLIDES_DEVELOPMENT: "false"

services:
  backendAction:
    environment:
      [...EMAIL_ENVS...]
  
  proxy:
    environment:
      EXTERNAL_ADDRESS: openslides.XXXXX.de
```

docker-compose.override.yml:
```
services:
  proxy:
    build:
      context: config/openslides-proxy
    ports:
      - "[::]:80:8001"
      - "[::]:443:8000"
      - "0.0.0.0:80:8001"
      - "0.0.0.0:443:8000"
    volumes:
      - "./data/proxy:/data/caddy"
      
  satosa:
    image: satosa
    restart: always
    entrypoint: gunicorn
    command: '-b0.0.0.0:8080 satosa.wsgi:app'
    volumes:
      - "./config/satosa:/etc/satosa"
    environment:
      BASE_URL: "https://satosa.openslides.XXXXXX.de"
      SATOSA_STATE_ENCRYPTION_KEY: "--------"
      SATOSA_OIDC_BACKEND_CLIENTID: "openslides.XXXXXX.de"
      SATOSA_OIDC_BACKEND_CLIENTSECRET: "------"
      SATOSA_OIDC_BACKEND_ISSUER: "https://SSO.XXXXXX.de"
    networks:
      - uplink
```

the proxy gets build from git clone, so the satosa.openslides. route can get prepended to the caddy_base.json routes. This is the only thing changed with the proxy and the satosa.openslides route works, so that additional route should not cause these problems. That was there with Traefik before and worked with the same error above.

The SAML endpoint only ever gets configured/referenced by its https:// external URL, so there cannot be a situation where the client tries to connect to the docker-url `satosa`or such things.
